// GENERATED by scripts/bundle-engine.mjs - do not edit by hand.
export const MANIFEST = {
  "files": [
    {
      "path": "engine/costing.js",
      "sha256": "9c4229377f8784432e4dd5a845bd18d449426f0259efa16cebf28838da8fbd25"
    },
    {
      "path": "engine/costingTables.js",
      "sha256": "0ce232d0caf757ff419aac5c488f53d451ff7496478ae4d3c470325222120913"
    },
    {
      "path": "engine/calcDefaults.js",
      "sha256": "c9df5fcb36e41b62631f394495c70c4d39e864535d583b5973f7c086c86976a1"
    },
    {
      "path": "engine/resolveAuthority.js",
      "sha256": "c21e3ab088ab8557344bdc5794e125e93df33d938b0c2e922c928126b39441b4"
    },
    {
      "path": "engine/interestBasis.js",
      "sha256": "d9616bfff710861ffb08b2dfe669897c52c52890b136202ef46f6d13fbe13500"
    }
  ],
  "digest": "7c2ceac1972460ba370ba423a2da8ddaae869e4361ff1ee9431f0f4a2ddcf09d",
  "engine_version": "engine/qe1-7c2ceac1972460ba"
};
