// GENERATED by scripts/bundle-engine.mjs - do not edit by hand.
export const MANIFEST = {
  "files": [
    {
      "path": "engine/costing.js",
      "sha256": "3d59a144f1fd41b86758bbac2bbf86039ac7076d51453f544e0e630bea14a9a4"
    },
    {
      "path": "engine/costingTables.js",
      "sha256": "0ce232d0caf757ff419aac5c488f53d451ff7496478ae4d3c470325222120913"
    },
    {
      "path": "engine/calcDefaults.js",
      "sha256": "c9df5fcb36e41b62631f394495c70c4d39e864535d583b5973f7c086c86976a1"
    },
    {
      "path": "engine/resolveAuthority.js",
      "sha256": "590cfcb6656ff277c48175e60c7f85ce19960792a5d5f0b63c97a611fa8767a3"
    },
    {
      "path": "engine/interestBasis.js",
      "sha256": "d9616bfff710861ffb08b2dfe669897c52c52890b136202ef46f6d13fbe13500"
    },
    {
      "path": "lib/constructionIdentity.js",
      "sha256": "1d112b55a1a04ca289efec9a81a15fda5ca2a61e6065569b82b37ee47a2602c8"
    }
  ],
  "digest": "600adcbe1a85be5914e6517fb838d599802028a248d2ca1dbe35e8dcafb95631",
  "engine_version": "engine/qe1-600adcbe1a85be59"
};
